# Generated by Django 5.0.2 on 2026-10-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_by', models.CharField(help_text='Who made the request.', max_length=200)),
                ('request_text', models.TextField(help_text='What was asked.')),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mcp_api_mcp_user_id_19a7b0_idx'), models.Index(fields=['follow_up_needed', '-created_at'], name='mcp_api_mcp_follow__43ba18_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_prefix', models.CharField(help_text='First characters shown in settings.', max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_access_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='mcp_api_per_token_h_cb627b_idx')],
            },
        ),
    ]
