# Generated by Django 5.0.2 on 2026-10-08 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_api', '0001_initial'),
        ('pages', '0028_project_brief_task_needs_review_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='name',
            field=models.CharField(default='Grok Bot', help_text='Agent name recorded on the activity log.', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(help_text='Token / agent name that made the change.', max_length=100)),
                ('action', models.CharField(max_length=40)),
                ('task_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='pages.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='pages.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'task activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='mcp_api_tas_project_4cfc61_idx'), models.Index(fields=['user', '-created_at'], name='mcp_api_tas_user_id_cc58b4_idx')],
            },
        ),
    ]
