# Generated by Django 5.0.2 on 2026-10-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_api', '0002_personalaccesstoken_name_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='personalaccesstoken',
            index=models.Index(fields=['user', 'name'], name='mcp_api_per_user_id_28c06e_idx'),
        ),
        migrations.AddConstraint(
            model_name='personalaccesstoken',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_mcp_token_name_per_user'),
        ),
    ]
