# Generated by Django 5.2.2 on 2026-10-10 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_api', '0003_alter_personalaccesstoken_user_and_more'),
        ('pages', '0028_project_brief_task_needs_review_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('task_text_snapshot', models.TextField(blank=True, default='')),
                ('agent_name', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=200)),
                ('request', models.CharField(help_text='What was asked, one line.', max_length=500)),
                ('action_summary', models.TextField()),
                ('decision', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('output_link', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending_review', max_length=20)),
                ('reviewer', models.CharField(blank=True, default='', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('entry_hash', models.CharField(blank=True, default='', max_length=64)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_entries', to='pages.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='mcp_api.decisionentry')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_entries', to='pages.task')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_entries', to='mcp_api.personalaccesstoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'decision entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mcp_api.decisionentry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionentry',
            index=models.Index(fields=['user', '-created_at'], name='mcp_api_dec_user_id_8a4a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionentry',
            index=models.Index(fields=['grid', '-created_at'], name='mcp_api_dec_grid_id_3f6733_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionentry',
            index=models.Index(fields=['status', '-created_at'], name='mcp_api_dec_status_d8fc87_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionentry',
            index=models.Index(fields=['agent_name', '-created_at'], name='mcp_api_dec_agent_n_4e8fab_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionreview',
            index=models.Index(fields=['entry', 'created_at'], name='mcp_api_dec_entry_i_553b18_idx'),
        ),
    ]
