# Generated by Django 5.2.2 on 2025-06-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_template_templatecolumnheader_templaterowheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='icon',
        ),
    ]
