# Generated by Django 5.0.2 on 2025-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_faq_contactsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='pages_task_project_c90bbf_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'order'], name='pages_task_project_64b03e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'row_header', 'column_header', 'order'], name='pages_task_project_85347d_idx'),
        ),
    ]
