# Generated by Django 5.2.2 on 2025-08-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', 'order']},
        ),
    ]
