# Generated by Django 5.0.2 on 2025-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_projectgroup_project_project_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='color',
            field=models.CharField(choices=[('#10B981', 'Green'), ('#ff714c', 'Orange'), ('#1F2937', 'Dark Gray'), ('#6B7280', 'Medium Gray'), ('#E5E7EB', 'Light Gray'), ('#F9FAFB', 'Very Light Gray')], default='#3B82F6', max_length=7),
        ),
    ]
