# Generated by Django 5.2.2 on 2025-08-18 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_projectgroup_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='color',
        ),
    ]
