# Generated by Django 5.2.2 on 2025-08-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_fix_existing_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='updated_at',
        ),
    ]
