# Generated by Django 5.2.2 on 2025-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_project_options_project_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
