# Generated by Django 5.2.2 on 2025-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_project_is_archived_archiveproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
