# Generated by Django 5.2.2 on 2025-08-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_societylink_name_societylink_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocietyLink',
        ),
    ]
