# Generated by Django 5.2.2 on 2025-08-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_delete_societylink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveProject',
        ),
    ]
