# Generated by Django 5.2.2 on 2025-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_delete_archiveproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
