# Generated by Django 5.2.2 on 2025-10-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_task_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamToadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_team_toad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='team_toad_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_toad_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='is_team_toad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['is_team_toad'], name='pages_proje_is_team_af6ff7_idx'),
        ),
        migrations.AddField(
            model_name='teamtoadtemplate',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_toad_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamtoadtemplate',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='member_of_team_toad_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teamtoadtemplate',
            index=models.Index(fields=['creator'], name='pages_teamt_creator_8d0a08_idx'),
        ),
    ]
