# Generated by Django 5.2.2 on 2025-10-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_task_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_toad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='team_toad',
            field=models.BooleanField(default=False),
        ),
    ]
