# Generated by Django 5.2.2 on 2025-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_project_team_toad_projectgroup_team_toad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team_toad',
            new_name='is_team_toad',
        ),
        migrations.RenameField(
            model_name='projectgroup',
            old_name='team_toad',
            new_name='is_team_toad',
        ),
    ]
