# Generated by Django 5.2.2 on 2025-10-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_tasknote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, help_text='Email address of the invited user (empty for shareable links)', max_length=254)),
                ('invitation_type', models.CharField(choices=[('email', 'Email Invitation'), ('link', 'Shareable Link')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('token', models.CharField(help_text='Unique token for the invitation', max_length=32, unique=True)),
                ('personal_message', models.TextField(blank=True, help_text='Optional personal message from the inviter')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tasknote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_archived'], name='pages_proje_user_id_39d37c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived', 'project_group', 'order'], name='pages_proje_is_arch_2638dd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_team_toad', 'is_archived'], name='pages_proje_is_team_43b997_idx'),
        ),
        migrations.AddField(
            model_name='gridinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gridinvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, help_text='User object if they have an account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gridinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pages.project'),
        ),
        migrations.AddIndex(
            model_name='gridinvitation',
            index=models.Index(fields=['token'], name='pages_gridi_token_16c7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='gridinvitation',
            index=models.Index(fields=['invited_email', 'status'], name='pages_gridi_invited_061cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='gridinvitation',
            index=models.Index(fields=['project', 'status'], name='pages_gridi_project_b7b260_idx'),
        ),
        migrations.AddIndex(
            model_name='gridinvitation',
            index=models.Index(fields=['expires_at'], name='pages_gridi_expires_a20672_idx'),
        ),
    ]
