# Generated by Django 5.2.2 on 2025-10-19 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_gridinvitation_alter_projectgroup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_toad_user',
            field=models.ManyToManyField(blank=True, related_name='team_toad_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
