# Generated by Django 5.2.2 on 2025-10-07 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_task_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_toad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_toad_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='team_toad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_toad_project_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['is_team_toad', 'team_toad_user'], name='pages_proje_is_team_961945_idx'),
        ),
    ]
