# Generated by Django 5.2.2 on 2026-01-24 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_project_team_toad_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltemplate',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users this template is shared with', related_name='shared_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
