# Generated by Django 5.2.2 on 2025-10-09 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_teamtoadtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectgroup',
            name='pages_proje_is_team_961945_idx',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='team_toad_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_toad_user',
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['is_team_toad'], name='pages_proje_is_team_af6ff7_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_toad_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_toad_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
