# Generated by Django 5.0.2 on 2026-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_add_shared_with_to_personaltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief',
            field=models.TextField(blank=True, default='', help_text='Standing context for this grid. Returned by get_grid so agents can see it.'),
        ),
        migrations.AddField(
            model_name='task',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Agent has handed this back for review.'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(choices=[('you', 'You'), ('agent', 'Agent')], default='you', help_text='Who currently owns this task: you, or an agent.', max_length=16),
        ),
    ]
