# Generated by Django 5.2.2 on 2025-10-12 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_projectgroup_pages_proje_is_team_961945_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_archived'], name='pages_proje_user_id_39d37c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived', 'project_group', 'order'], name='pages_proje_is_arch_2638dd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_team_toad', 'is_archived'], name='pages_proje_is_team_43b997_idx'),
        ),
    ]
