# Generated by Django 5.2.2 on 2025-10-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_gridinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gridinvitation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gridinvitation',
            name='invited_email',
            field=models.EmailField(blank=True, help_text='Email address of the invited user (empty for shareable links)', max_length=254),
        ),
    ]
