# Generated by Django 5.0.2 on 2025-07-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_betatester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betatester',
            old_name='date_joined',
            new_name='date_requested',
        ),
    ]
