# Generated by Django 5.2.2 on 2025-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('personal', 'Personal'), ('pro', 'Pro'), ('beta', 'Beta')], default='beta', max_length=35),
        ),
        migrations.DeleteModel(
            name='UserTier',
        ),
    ]
