# Generated by Django 5.2.2 on 2025-09-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_trial_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
    ]
