# Generated by Django 5.2.2 on 2025-09-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaTester',
        ),
    ]
