# Generated by Django 5.2.2 on 2025-09-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_societyuniversity_societylink_society_university'),
        ('accounts', '0011_delete_betatester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CRM.societylink'),
        ),
        migrations.AddField(
            model_name='user',
            name='associated_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.societyuniversity'),
        ),
    ]
