# Generated by Django 5.2.2 on 2025-09-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_associated_society_user_associated_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('personal', 'Personal'), ('personal_trial', 'Personal Trial'), ('pro', 'Pro'), ('beta', 'Beta')], default='beta', max_length=35),
        ),
    ]
