# Generated by Django 5.2.2 on 2025-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_grid_created',
            field=models.BooleanField(default=False, help_text='Whether the user has created their second grid.'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_grid_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the user has received the email about their second grid.'),
        ),
    ]
