# Generated by Django 5.2.2 on 2025-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_second_grid_created_user_second_grid_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regular_user',
            field=models.BooleanField(default=False, help_text='Whether the user is a regular user.'),
        ),
    ]
