# Generated by Django 5.2.2 on 2025-09-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscribed',
            field=models.BooleanField(default=True, help_text='Whether the user has subscribed to the email list.'),
        ),
    ]
