# Generated by Django 5.2.2 on 2025-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_email_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('personal', 'Personal'), ('personal_trial', 'Personal Trial'), ('personal_3_month_trial', 'Personal 3 Month Trial'), ('pro', 'Pro'), ('pro_trial', 'Pro Trial'), ('society_pro', 'Society Pro'), ('beta', 'Beta')], default='beta', max_length=35),
        ),
    ]
