# Generated by Django 5.2.2 on 2025-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the user has received the 2-day follow-up email.'),
        ),
    ]
