# Generated by Django 5.2.2 on 2025-10-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_second_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_type',
            field=models.CharField(blank=True, choices=[('3_month', '3 Month'), ('6_month', '6 Month')], help_text='Type of trial period for Pro users.', max_length=20, null=True),
        ),
    ]
