# Generated by Django 5.2.2 on 2025-10-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_trial_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_email_sent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_grid_email_sent',
        ),
    ]
