# Generated by Django 5.2.2 on 2025-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('personal', 'Personal'), ('personal_trial', 'Personal Trial'), ('personal_3_month_trial', 'Personal 3 Month Trial'), ('pro', 'Team Toad'), ('pro_trial', 'Team Toad Trial'), ('society_pro', 'Society Team Toad'), ('beta', 'Beta')], default='beta', max_length=35),
        ),
    ]
