# Generated by Django 5.2.2 on 2025-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trial_type',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_month', '3 Month'), ('6_month', '6 Month')], help_text='Type of trial period for Pro users.', max_length=20, null=True),
        ),
    ]
