# Generated by Django 5.2.2 on 2025-12-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_trial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user if this user is part of a team subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubscriptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID for this team subscription.', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of subscriptions purchased.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription group is active.')),
                ('admin', models.ForeignKey(help_text='The admin user who manages this subscription group.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_subscription_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Team members in this subscription group.', related_name='subscription_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(help_text='Email address of the invited user.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Status of the invitation.', max_length=10)),
                ('token', models.CharField(help_text='Unique token for the invitation.', max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted.', null=True)),
                ('invited_by', models.ForeignKey(help_text='The admin who sent this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, help_text='User object if they have an account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('subscription_group', models.ForeignKey(help_text='The subscription group this invitation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.subscriptiongroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptiongroup',
            index=models.Index(fields=['admin', 'is_active'], name='accounts_su_admin_i_09ab65_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiongroup',
            index=models.Index(fields=['stripe_subscription_id'], name='accounts_su_stripe__c1db61_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['token'], name='accounts_te_token_8d263f_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['invited_email', 'status'], name='accounts_te_invited_e8f042_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['subscription_group', 'status'], name='accounts_te_subscri_6bf11e_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['expires_at'], name='accounts_te_expires_39efa7_idx'),
        ),
    ]
