# Generated by Django 5.2.2 on 2025-01-XX XX:XX

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_team_admin_subscriptiongroup_teaminvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the login code', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Code expiration time')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested the code', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='logincode',
            index=models.Index(fields=['user', 'expires_at'], name='accounts_lo_user_id_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='logincode',
            index=models.Index(fields=['code_hash', 'expires_at'], name='accounts_lo_code_ha_expires_idx'),
        ),
    ]

