# Generated by Django 5.2.2 on 2026-01-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_logincode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logincode',
            new_name='accounts_lo_user_id_d0b959_idx',
            old_name='accounts_lo_user_id_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='logincode',
            new_name='accounts_lo_code_ha_0cc406_idx',
            old_name='accounts_lo_code_ha_expires_idx',
        ),
    ]
