# Generated by Django 5.0.2 on 2025-08-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='leadmessage',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CRM.lead'),
        ),
    ]
