# Generated by Django 5.2.2 on 2025-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_societylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societylink',
            name='url',
        ),
        migrations.RemoveField(
            model_name='societylink',
            name='url_expires_at',
        ),
        migrations.AlterField(
            model_name='societylink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='society_links/'),
        ),
    ]
