# Generated by Django 5.2.2 on 2025-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_remove_societylink_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societylink',
            name='url_identifier',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
