# Generated by Django 5.2.2 on 2025-08-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_societylink_url_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societylink',
            name='url_identifier',
        ),
    ]
