# Generated by Django 5.2.2 on 2025-08-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_societylink_url_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societylink',
            options={},
        ),
        migrations.RemoveField(
            model_name='societylink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='societylink',
            name='updated_at',
        ),
    ]
