# Generated by Django 5.2.2 on 2025-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_societylink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSocietyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='test_society_links/')),
            ],
        ),
    ]
