# Generated by Django 5.2.2 on 2025-08-28 20:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_testsocietylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='societylink',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='society_links/'),
        ),
        migrations.AlterField(
            model_name='testsocietylink',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='test_society_links/'),
        ),
    ]
