# Generated by Django 5.2.2 on 2025-09-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_societyuniversity_societylink_society_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='society_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.societyuniversity'),
        ),
    ]
