# Generated by Django 5.2.2 on 2025-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_lead_society_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='toad_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='toad_customer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
