# Generated by Django 5.2.2 on 2025-09-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_lead_toad_customer_lead_toad_customer_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleTestModel',
        ),
        migrations.DeleteModel(
            name='TestSocietyLink',
        ),
        migrations.AddField(
            model_name='lead',
            name='society_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.societylink'),
        ),
    ]
