# Generated by Django 5.2.2 on 2025-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_delete_simpletestmodel_delete_testsocietylink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='initial_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_message_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
