# Generated by Django 5.2.2 on 2025-09-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_lead_initial_message_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societyuniversity',
            options={'ordering': ['name']},
        ),
    ]
