# Generated by Django 5.2.2 on 2025-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_alter_societyuniversity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='society_link',
        ),
    ]
