# Generated by Django 5.2.2 on 2025-09-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_remove_lead_society_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='societylink',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.lead'),
        ),
    ]
