# Generated by Django 5.2.2 on 2025-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_societylink_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
