# Generated by Django 5.2.2 on 2025-09-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_alter_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadfocus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
