# Generated by Django 5.2.2 on 2025-09-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_alter_contactmethod_name_alter_lead_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
