# Generated by Django 5.2.2 on 2025-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_alter_lead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='no_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='no_response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
