# Generated by Django 5.2.2 on 2025-10-11 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0022_lead_no_response_lead_no_response_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text="Optional - only if you'd like us to follow up", max_length=254, null=True)),
                ('regularly_using_toad', models.BooleanField(help_text='Select Yes if you use Toad regularly, No if not', verbose_name='Are you regularly using Toad?')),
                ('usage_reason', models.TextField(blank=True, help_text='Tell us about your experience with Toad', verbose_name='If yes, why? If not, why not?')),
                ('organization_method', models.CharField(blank=True, choices=[('notes_phone', 'Notes on phone'), ('pen_paper', 'Pen and paper'), ('trello', 'Trello'), ('monday', 'Monday.com'), ('excel', 'Excel'), ('other', 'Other')], max_length=50, verbose_name='How do you tend to organise?')),
                ('organization_other', models.CharField(blank=True, max_length=200, verbose_name='If other, please specify')),
                ('non_user_suggestion', models.TextField(blank=True, help_text='What would convince you to use Toad?', verbose_name="If you're not using Toad, is there anything that would make you use it?")),
                ('user_improvement', models.TextField(blank=True, help_text='How can we improve Toad for you?', verbose_name='If you are using Toad, what could make it better?')),
                ('team_toad_interest', models.TextField(blank=True, help_text='Team features for collaborative planning', verbose_name='Would you be interested in Team Toad?')),
                ('would_share', models.BooleanField(default=False, verbose_name='Would you share Toad with friends and/or colleagues?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
