# Generated by Django 5.2.2 on 2025-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, help_text="Optional - share your name if you'd like", max_length=200),
        ),
    ]
