# Generated by Django 5.2.2 on 2025-10-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0024_remove_feedback_email_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='organization_method',
            field=models.CharField(blank=True, choices=[('toad', 'Toad'), ('notes_phone', 'Notes on phone'), ('pen_paper', 'Pen and paper'), ('trello', 'Trello'), ('monday', 'Monday.com'), ('excel', 'Excel'), ('other', 'Other')], max_length=50, verbose_name='How do you tend to organise?'),
        ),
    ]
