# Generated by Django 5.2.2 on 2025-10-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0025_alter_feedback_organization_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='testimonial_first_name',
            field=models.CharField(blank=True, help_text='Your first name to display with the quote', max_length=100, verbose_name='First name for testimonial'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='testimonial_job_title',
            field=models.CharField(blank=True, help_text='Your job title to display with the quote', max_length=200, verbose_name='Job title for testimonial'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='testimonial_quote',
            field=models.TextField(blank=True, help_text='Share why you love Toad - we may feature this on our website!', verbose_name='Would you like to provide a testimonial quote?'),
        ),
    ]
