# Generated by Django 5.2.2 on 2025-10-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0027_company_companysector_lead_lead_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contactmethod'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.leadfocus'),
        ),
    ]
