# Generated by Django 5.2.2 on 2025-11-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0028_alter_lead_contact_method_alter_lead_lead_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('text', models.TextField(help_text='Template body text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='companysector',
            options={'ordering': ['name'], 'verbose_name': 'Company Sector', 'verbose_name_plural': 'Company Sectors'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_email_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_email_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_email_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='personalised_email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='CRM.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='CRM.emailtemplate'),
        ),
        migrations.DeleteModel(
            name='B2BLink',
        ),
    ]
