# Generated by Django 5.2.2 on 2025-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0029_emailtemplate_alter_companysector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companysector',
            name='landing_page_template',
            field=models.CharField(blank=True, help_text="Optional HTML template path for this sector's landing page (e.g. 'business_links/events/toad_weddings.html').", max_length=255),
        ),
    ]
