# Generated by Django 5.2.2 on 2025-11-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0030_company_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='CRM.companysector'),
        ),
        migrations.AddField(
            model_name='companysector',
            name='sector_type',
            field=models.CharField(choices=[('event', 'Event'), ('wedding', 'Wedding'), ('other', 'Other')], default='other', help_text='Controls which landing page template is used for this sector.', max_length=20),
        ),
    ]
