# Generated by Django 5.2.2 on 2025-11-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0031_company_sector_companysector_sector_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='companysector',
            name='landing_page_template',
        ),
        migrations.RemoveField(
            model_name='companysector',
            name='sector_type',
        ),
    ]
