# Generated by Django 5.2.2 on 2025-11-20 20:56

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0032_remove_company_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(help_text='The name of the playbook', max_length=100)),
                ('main_header_description', models.TextField(help_text='The description of the header')),
                ('video_1', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='customer_templates/')),
                ('used_by', models.CharField(help_text='Used by event teams, venues and planners', max_length=100)),
                ('grid_header', models.CharField(help_text='What Toad looks like for [x]', max_length=100)),
                ('grid_1_title', models.CharField(help_text='The title of the first grid', max_length=100)),
                ('grid_1_header_description', models.TextField(help_text='The description of the header')),
                ('grid_1_subheader', models.CharField(help_text='The subheader of the first grid', max_length=100)),
                ('grid_1_bullet_1', models.CharField(help_text='The first bullet point of the first grid', max_length=100)),
                ('grid_1_bullet_2', models.CharField(help_text='The second bullet point of the first grid', max_length=100)),
                ('grid_1_bullet_3', models.CharField(help_text='The third bullet point of the first grid', max_length=100)),
                ('grid_1_bullet_4', models.CharField(help_text='The fourth bullet point of the first grid', max_length=100)),
                ('grid_1_video', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='customer_templates/')),
                ('grid_2_title', models.CharField(help_text='The title of the second grid', max_length=100)),
                ('grid_2_header_description', models.TextField(help_text='The description of the header')),
                ('grid_2_subheader', models.CharField(help_text='The subheader of the second grid', max_length=100)),
                ('grid_2_bullet_1', models.CharField(help_text='The first bullet point of the second grid', max_length=100)),
                ('grid_2_bullet_2', models.CharField(help_text='The second bullet point of the second grid', max_length=100)),
                ('grid_2_bullet_3', models.CharField(help_text='The third bullet point of the second grid', max_length=100)),
                ('grid_2_bullet_4', models.CharField(help_text='The fourth bullet point of the second grid', max_length=100)),
                ('grid_2_video', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='customer_templates/')),
                ('grid_3_title', models.CharField(help_text='The title of the third grid', max_length=100)),
                ('grid_3_header_description', models.TextField(help_text='The description of the header')),
                ('grid_3_subheader', models.CharField(help_text='The subheader of the third grid', max_length=100)),
                ('grid_3_bullet_1', models.CharField(help_text='The first bullet point of the third grid', max_length=100)),
                ('grid_3_bullet_2', models.CharField(help_text='The second bullet point of the third grid', max_length=100)),
                ('grid_3_bullet_3', models.CharField(help_text='The third bullet point of the third grid', max_length=100)),
                ('grid_3_bullet_4', models.CharField(help_text='The fourth bullet point of the third grid', max_length=100)),
                ('grid_3_video', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='customer_templates/')),
                ('section_2_title', models.CharField(help_text='Why venues love Toad', max_length=100)),
                ('section_2_card_1_title', models.CharField(help_text='The title of the first card', max_length=100)),
                ('section_2_card_1_description', models.TextField(help_text='The description of the first card')),
                ('section_2_card_2_title', models.CharField(help_text='The title of the second card', max_length=100)),
                ('section_2_card_2_description', models.TextField(help_text='The description of the second card')),
                ('section_2_card_3_title', models.CharField(help_text='The title of the third card', max_length=100)),
                ('section_2_card_3_description', models.TextField(help_text='The description of the third card')),
                ('section_2_card_4_title', models.CharField(help_text='The title of the fourth card', max_length=100)),
                ('section_2_card_4_description', models.TextField(help_text='The description of the fourth card')),
                ('company_sector', models.ForeignKey(blank=True, help_text='The company sector this template is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_templates', to='CRM.companysector')),
            ],
        ),
    ]
