# Generated by Django 5.2.2 on 2025-11-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0033_customertemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='company',
            name='company_sector',
            field=models.ForeignKey(blank=True, help_text='The company sector this company is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='CRM.companysector'),
        ),
    ]
