# Generated by Django 5.2.2 on 2025-11-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0034_alter_company_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
