# Generated by Django 5.2.2 on 2025-12-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0035_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='template_view_count',
            field=models.IntegerField(default=0, help_text="Number of times this company's template has been viewed"),
        ),
        migrations.AddField(
            model_name='leadmessage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CRM.company'),
        ),
        migrations.AddConstraint(
            model_name='leadmessage',
            constraint=models.CheckConstraint(check=models.Q(('lead__isnull', False), ('company__isnull', False), _connector='OR'), name='lead_or_company_required'),
        ),
    ]
