# Generated by Django 5.2.2 on 2025-12-02 20:06

from django.db import migrations


def noop(apps, schema_editor):
    # This migration is a no-op - template_view_count was already added in 0036
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0036_customertemplate_view_count_leadmessage_company_and_more'),
    ]

    operations = [
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
