# Generated by Django 5.2.2 on 2025-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0036_customertemplate_view_count_leadmessage_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='template_view_count',
            field=models.IntegerField(default=0, help_text="Number of times this company's template has been viewed"),
        ),
    ]
