# Generated by Django 5.2.2 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0037_company_template_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertemplate',
            name='view_count',
        ),
    ]
