# Generated by Django 5.2.2 on 2025-12-02 20:09

from django.db import migrations


def noop(apps, schema_editor):
    # This migration is a no-op - view_count was never added to CustomerTemplate
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0037_company_template_view_count'),
    ]

    operations = [
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
