# Generated by Django 5.2.2 on 2025-12-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0038_remove_customertemplate_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_status',
            field=models.CharField(blank=True, choices=[('Initial', 'Initial'), ('Initial Follow Up', 'Initial Follow Up'), ('Secondary Follow Up', 'Secondary Follow Up'), ('Tertiary Follow Up', 'Tertiary Follow Up')], null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Prospect', 'Prospect'), ('Rejected but follow up', 'Rejected but follow up'), ('No response', 'No response'), ('Rejected', 'Rejected')], default='Prospect'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
