# Generated by Django 5.2.2 on 2025-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0039_company_email_status_company_status_lead_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_status',
            field=models.CharField(blank=True, choices=[('Init', 'Init'), ('Init FP', 'Init FP'), ('Sec FP', 'Sec FP'), ('Ter FP', 'Ter FP')], null=True),
        ),
    ]
