# Generated by Django 5.2.2 on 2025-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0040_alter_company_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_status',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
    ]
