# Generated by Django 5.2.2 on 2026-01-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0041_alter_company_email_status'),
    ]

    operations = [
        # First, add all new fields to Company
        migrations.AddField(
            model_name='company',
            name='email_failed_date',
            field=models.DateField(blank=True, help_text='Date of last email send failure', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='first_email_message_id',
            field=models.CharField(blank=True, help_text='Message-ID header from first email, used for threading subsequent emails', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='fourth_email_sent_date',
            field=models.DateField(blank=True, help_text='Date fourth/final email was sent', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='second_email_sent_date',
            field=models.DateField(blank=True, help_text='Date second follow-up email was sent', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='third_email_sent_date',
            field=models.DateField(blank=True, help_text='Date third follow-up email was sent', null=True),
        ),
        
        # Add new fields to EmailTemplate BEFORE altering unique_together
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Email body text. Use {company_name}, {contact_person}, {personalised_template_url} for personalization'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='company_sector',
            field=models.ForeignKey(blank=True, help_text='The sector this template belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='CRM.companysector'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_number',
            field=models.IntegerField(choices=[(1, 'Email 1 (Initial)'), (2, 'Email 2 (Follow-up 1)'), (3, 'Email 3 (Follow-up 2)'), (4, 'Email 4 (Final)')], default=1, help_text='Which email in the sequence (1-4)'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Email subject line. Use {company_name}, {contact_person} for personalization', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Internal name for this template', max_length=150),
        ),
        
        # Remove old text field
        migrations.RemoveField(
            model_name='emailtemplate',
            name='text',
        ),
        
        # NOW alter model options and unique_together (after fields exist)
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['company_sector', 'email_number'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('company_sector', 'email_number')},
        ),
    ]
