# Generated by Django 5.2.2 on 2026-01-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0042_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_email_subject',
            field=models.CharField(blank=True, help_text="Subject of first email, follow-ups use 'Re: [this subject]' for threading", max_length=255),
        ),
    ]
