# Generated by Django 5.2.2 on 2026-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0043_company_first_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_email_body',
            field=models.TextField(blank=True, help_text='Body of the last email sent, used to quote in follow-up replies'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_email_date',
            field=models.DateTimeField(blank=True, help_text="DateTime of the last email sent, used for 'On [date], [name] wrote:' quote", null=True),
        ),
    ]
