# Generated by Django 5.2.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0044_company_last_email_body_company_last_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='template_sign_up_click_count',
            field=models.IntegerField(default=0, help_text="Number of times sign-up links were clicked on this company's template"),
        ),
    ]

