# Generated by Django 5.2.2 on 2026-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0045_company_template_sign_up_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='call_made',
            field=models.BooleanField(default=False),
        ),
    ]
